services:
  image-generator:
    container_name: image-generator
    build: .
    ports:
      - "8484:8484"
    volumes:
      - ./local_models:/app/local_models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
